version: "3"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - 6379
    restart: always
  server:
    build:
      context: .
    ports:
      - 8080:8080
    expose:
      - 8080
    restart: always
